### ISSUE TITLE
wrong IP in readme

### ISSUE THREAD

**Issue by rluetke** [ryanwrightdevel/vagrant-puppet-zendframework#1]
IP mismatch: readme = 192.168.33.13 (not working), vagrantfile = 192.168.33.12 (working).
http://192.168.33.12/ = ZF2 Skeleton Application working out of the box! Great!
Thanks, Ralf

**Comment by ryanwrightdevel** [comment]
I didn't think anyone else was using this besides myself. So thanks for the feedback. I'll get this updated. If you've found any other issues just let me know.
